version: '2'
# dockerfile for DockerHub image test

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.build
    command: test --info
    volumes:
      - .:/build
      - $HOME/.m2:/root/.m2
      - $HOME/.gradle:/root/.gradle
      - /var/run/docker.sock:/var/run/docker.sock