# for tests that are run via docker compose gradle plugin for integration test dependencies
version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "5672"
      - "15672"